function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Factorial_while"};
	this.sidHashMap["Factorial_while"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Factorial_while:20"};
	this.sidHashMap["Factorial_while:20"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "Factorial_while:47"};
	this.sidHashMap["Factorial_while:47"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/Constant"] = {sid: "Factorial_while:38"};
	this.sidHashMap["Factorial_while:38"] = {rtwname: "<Root>/Constant"};
	this.rtwnameHashMap["<Root>/Constant1"] = {sid: "Factorial_while:40"};
	this.sidHashMap["Factorial_while:40"] = {rtwname: "<Root>/Constant1"};
	this.rtwnameHashMap["<Root>/Display"] = {sid: "Factorial_while:51"};
	this.sidHashMap["Factorial_while:51"] = {rtwname: "<Root>/Display"};
	this.rtwnameHashMap["<Root>/While Iterator Subsystem"] = {sid: "Factorial_while:20"};
	this.sidHashMap["Factorial_while:20"] = {rtwname: "<Root>/While Iterator Subsystem"};
	this.rtwnameHashMap["<Root>/y"] = {sid: "Factorial_while:41"};
	this.sidHashMap["Factorial_while:41"] = {rtwname: "<Root>/y"};
	this.rtwnameHashMap["<S1>/IC"] = {sid: "Factorial_while:39"};
	this.sidHashMap["Factorial_while:39"] = {rtwname: "<S1>/IC"};
	this.rtwnameHashMap["<S1>/Num"] = {sid: "Factorial_while:48"};
	this.sidHashMap["Factorial_while:48"] = {rtwname: "<S1>/Num"};
	this.rtwnameHashMap["<S1>/GreaterThan"] = {sid: "Factorial_while:68"};
	this.sidHashMap["Factorial_while:68"] = {rtwname: "<S1>/GreaterThan"};
	this.rtwnameHashMap["<S1>/MATLAB Function"] = {sid: "Factorial_while:47"};
	this.sidHashMap["Factorial_while:47"] = {rtwname: "<S1>/MATLAB Function"};
	this.rtwnameHashMap["<S1>/Unit Delay"] = {sid: "Factorial_while:50"};
	this.sidHashMap["Factorial_while:50"] = {rtwname: "<S1>/Unit Delay"};
	this.rtwnameHashMap["<S1>/While Iterator"] = {sid: "Factorial_while:23"};
	this.sidHashMap["Factorial_while:23"] = {rtwname: "<S1>/While Iterator"};
	this.rtwnameHashMap["<S1>/y"] = {sid: "Factorial_while:49"};
	this.sidHashMap["Factorial_while:49"] = {rtwname: "<S1>/y"};
	this.rtwnameHashMap["<S2>:1"] = {sid: "Factorial_while:47:1"};
	this.sidHashMap["Factorial_while:47:1"] = {rtwname: "<S2>:1"};
	this.rtwnameHashMap["<S2>:1:2"] = {sid: "Factorial_while:47:1:2"};
	this.sidHashMap["Factorial_while:47:1:2"] = {rtwname: "<S2>:1:2"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
